export const teamsData = [
  {
    id: 'chennai-super-kings',
    name: 'Chennai Super Kings',
    shortName: 'CSK',
    color1: '#F9CD05',
    color2: '#FF9900',
    logo: 'https://placehold.co/200x200/F9CD05/000?text=CSK',
    banner: 'https://placehold.co/1200x400/F9CD05/000?text=CSK+Banner',
    captain: 'Ruturaj Gaikwad',
    stadium: 'M.A. Chidambaram Stadium',
    trophies: 5,
    squad: ['MS Dhoni', 'Ravindra Jadeja', 'Shivam Dube', 'Matheesha Pathirana']
  },
  {
    id: 'mumbai-indians',
    name: 'Mumbai Indians',
    shortName: 'MI',
    color1: '#004BA0',
    color2: '#002B5E',
    logo: 'https://placehold.co/200x200/004BA0/FFF?text=MI',
    banner: 'https://placehold.co/1200x400/004BA0/FFF?text=MI+Banner',
    captain: 'Hardik Pandya',
    stadium: 'Wankhede Stadium',
    trophies: 5,
    squad: ['Rohit Sharma', 'Jasprit Bumrah', 'Suryakumar Yadav', 'Tim David']
  },
  {
    id: 'royal-challengers-bengaluru',
    name: 'Royal Challengers Bengaluru',
    shortName: 'RCB',
    color1: '#EC1C24',
    color2: '#2B2A29',
    logo: 'https://placehold.co/200x200/EC1C24/FFF?text=RCB',
    banner: 'https://placehold.co/1200x400/EC1C24/FFF?text=RCB+Banner',
    captain: 'Faf du Plessis',
    stadium: 'M. Chinnaswamy Stadium',
    trophies: 0,
    squad: ['Virat Kohli', 'Glenn Maxwell', 'Mohammed Siraj', 'Cameron Green']
  },
  {
    id: 'kolkata-knight-riders',
    name: 'Kolkata Knight Riders',
    shortName: 'KKR',
    color1: '#3A225D',
    color2: '#1D112E',
    logo: 'https://placehold.co/200x200/3A225D/FFF?text=KKR',
    banner: 'https://placehold.co/1200x400/3A225D/FFF?text=KKR+Banner',
    captain: 'Shreyas Iyer',
    stadium: 'Eden Gardens',
    trophies: 2,
    squad: ['Sunil Narine', 'Andre Russell', 'Rinku Singh', 'Mitchell Starc']
  },
  {
    id: 'rajasthan-royals',
    name: 'Rajasthan Royals',
    shortName: 'RR',
    color1: '#EA1A85',
    color2: '#254AA5',
    logo: 'https://placehold.co/200x200/EA1A85/FFF?text=RR',
    banner: 'https://placehold.co/1200x400/EA1A85/FFF?text=RR+Banner',
    captain: 'Sanju Samson',
    stadium: 'Sawai Mansingh Stadium',
    trophies: 1,
    squad: ['Jos Buttler', 'Yashasvi Jaiswal', 'Yuzvendra Chahal', 'Trent Boult']
  },
  {
    id: 'sunrisers-hyderabad',
    name: 'Sunrisers Hyderabad',
    shortName: 'SRH',
    color1: '#F26522',
    color2: '#000000',
    logo: 'https://placehold.co/200x200/F26522/FFF?text=SRH',
    banner: 'https://placehold.co/1200x400/F26522/FFF?text=SRH+Banner',
    captain: 'Pat Cummins',
    stadium: 'Rajiv Gandhi Intl Stadium',
    trophies: 1,
    squad: ['Travis Head', 'Heinrich Klaasen', 'Bhuvneshwar Kumar', 'Abhishek Sharma']
  },
  {
    id: 'delhi-capitals',
    name: 'Delhi Capitals',
    shortName: 'DC',
    color1: '#00008B',
    color2: '#EF1B23',
    logo: 'https://placehold.co/200x200/00008B/FFF?text=DC',
    banner: 'https://placehold.co/1200x400/00008B/FFF?text=DC+Banner',
    captain: 'Rishabh Pant',
    stadium: 'Arun Jaitley Stadium',
    trophies: 0,
    squad: ['David Warner', 'Axar Patel', 'Kuldeep Yadav', 'Mitchell Marsh']
  },
  {
    id: 'punjab-kings',
    name: 'Punjab Kings',
    shortName: 'PBKS',
    color1: '#ED1B24',
    color2: '#D1AB3E',
    logo: 'https://placehold.co/200x200/ED1B24/FFF?text=PBKS',
    banner: 'https://placehold.co/1200x400/ED1B24/FFF?text=PBKS+Banner',
    captain: 'Shikhar Dhawan',
    stadium: 'PCA Stadium, Mohali',
    trophies: 0,
    squad: ['Kagiso Rabada', 'Arshdeep Singh', 'Liam Livingstone', 'Sam Curran']
  },
  {
    id: 'gujarat-titans',
    name: 'Gujarat Titans',
    shortName: 'GT',
    color1: '#1B2133',
    color2: '#B89C57',
    logo: 'https://placehold.co/200x200/1B2133/FFF?text=GT',
    banner: 'https://placehold.co/1200x400/1B2133/FFF?text=GT+Banner',
    captain: 'Shubman Gill',
    stadium: 'Narendra Modi Stadium',
    trophies: 1,
    squad: ['Rashid Khan', 'David Miller', 'Rahul Tewatia', 'Mohammed Shami']
  },
  {
    id: 'lucknow-super-giants',
    name: 'Lucknow Super Giants',
    shortName: 'LSG',
    color1: '#00008B',
    color2: '#00BFFF',
    logo: 'https://placehold.co/200x200/00008B/FFF?text=LSG',
    banner: 'https://placehold.co/1200x400/00008B/FFF?text=LSG+Banner',
    captain: 'KL Rahul',
    stadium: 'Ekana Cricket Stadium',
    trophies: 0,
    squad: ['Quinton de Kock', 'Nicholas Pooran', 'Marcus Stoinis', 'Ravi Bishnoi']
  }
];
